services:
  api:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "5018:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=BookingDb;"
      Redis__Enabled: "true"
      Redis__ConnectionString: "redis:6379"
      Elasticsearch__Enabled: "true"
      Elasticsearch__Url: "http://elasticsearch:9200"
      FileStorage__Provider: "Local"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - booking-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BookingDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - booking-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - booking-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - booking-net

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - booking-net

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - booking-net

volumes:
  pgdata:
  esdata:

networks:
  booking-net:
    driver: bridge
