apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-api-ingress
  namespace: booking-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.bookingsmart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booking-api-service
                port:
                  number: 80
