apiVersion: v1
kind: Secret
metadata:
  name: booking-api-secrets
  namespace: booking-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  ConnectionStrings__DefaultConnection: "User ID=postgres;Password=CHANGE_ME;Host=postgres-service;Port=5432;Database=BookingDb;"
  Jwt__Secret: "your-super-secret-key-here-min-32-chars-long!!!"
  AwsS3__AccessKey: "YOUR_AWS_ACCESS_KEY"
  AwsS3__SecretKey: "YOUR_AWS_SECRET_KEY"
